### ISSUE TITLE
SMS limit

### ISSUE THREAD

**Issue by simplyniceweb** [globelabs/api#4]
I'm not certain if it's still 10 SMS per day since the one in the tutorial i read was 2 years ago so i want to confirm it here, how many SMS i can make/send per day? and how many SMS i can receive per day?

Reference:
http://www.rofus.net/2013/01/sms-notification-via-globe-labs.html

Thanks in advance!

**Comment by engrbugs** [comment]
hi is there a code that working sending sms using globe labs api? preferably c# much appreciated! i cannot understand the code... and i do not have the id and the secret code, but i have sign up for globe labs. thanks! all i see in github was a code but not working sms sender...

**Comment by amsantos** [comment]
You can check this github repo:
https://github.com/globelabs/globe-api-csharp .

You can get the API key and secret, when you "Create an App" at the
developer portal (http://developer.globelabs.com.ph/apps/new) .

For API inquiry, email api@globelabsbeta.com

**Comment by engrbugs** [comment]
hi what is the problem with my code???

 string app_id = "{{qp4bIXpRxxxxxxxxxxapeLI8EE}}";
            string app_secret = "{{18a73ae0a4a085328133978a9xxxxxxxxxx825d1b3adc9ae87e0587}}";

            var short_code = "{{75x0}}";

            var auth_code = "{{CODE_PUSHED_BY_GLOBE_SYSTEM}}";

            var auth = GlobeApi.Auth(app_id, app_secret);

            Console.WriteLine("Login Url: ");
            Console.WriteLine(auth.getLoginUrl());
            Console.WriteLine("");

            Console.WriteLine("Get Access Token:");
            dynamic access_token = auth.getAccessToken(auth_code).access_token;
            Console.WriteLine(access_token);
            Console.WriteLine("");

            var sms = GlobeApi.Sms(short_code);

            Console.WriteLine("Send SMS Message:");
            dynamic smsResponse = sms.sendMessage(access_token, "{{0917xxxxx28}}", "Test Message");
            Console.WriteLine(smsResponse);
            Console.WriteLine("");

            var payment = GlobeApi.Payment(access_token, "{{0917xxxxx28}}");

            Console.WriteLine("Send Payment Request:");
            dynamic paymentResponse = payment.charge("0.00", "54630000006");
            Console.WriteLine(paymentResponse);

            Console.Read();

**Comment by engrbugs** [comment]
got it bro... where should i get the code? var auth_code = "{{CODE_PUSHED_BY_GLOBE_SYSTEM}}"; i have my app id my secret. the code is missing for the access token recipe hehehe

**Comment by biansor** [comment]
Hi i am beginner in creating sms api in php, i don't know what exactly to do i don't even know the codes that i download from here [https://github.com/globelabs/api](url) i need globe charging payment via sms or gcash for my thesis please help me

**Comment by engrbugs** [comment]
Hi I don't use php I only use c#. Just try and try, after how many tries I actually got it running. I only successfully ‎tries are the sms sending and sim location. Gcash charging was not my priority. Good luck                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        From: biansorSent: Tuesday, May 24, 2016 2:56 AMTo: globelabs/apiReply To: globelabs/apiCc: engrbugs; CommentSubject: Re: [globelabs/api] SMS limit (#4)Hi i am beginner in creating sms api in php, i don't know what exactly to do i don't even know the codes that i download from here https://github.com/globelabs/api i need globe charging payment via sms or gcash for my thesis please help me

—You are receiving this because you commented.Reply to this email directly or view it on GitHub

**Comment by adin234** [comment]
@biansor the PHP sample codes has everything you need. there is a sample code [uploaded](https://github.com/globelabs/api/blob/master/PHP/test/index.php) you can just follow that and you should be fine. it has samples for authentication, sending sms and charging

**Comment by biansor** [comment]
tnx for your suggestion now i need help, i can send now a text message to my phone but only on the globelabs site which i created an account, i try the sample codes it works but instead of sending text message to my phone it redirects me to developer.globelabs.com.ph
![help](https://cloud.githubusercontent.com/assets/19538012/15517878/b6435462-222c-11e6-8ca9-e5079aa0f0d3.jpg)

**Comment by adin234** [comment]
@biansor yes, that will happen because you are invoking a web auth flow. https://github.com/globelabs/api/blob/master/PHP/docs/sms.md#authentication

if you want to get an access token without using that flow, just use your mobile phone and send `INFO` to your shortcode, it will then send you a message then just reply `YES` to it and you will receive an access token in your notify url

**Comment by biansor** [comment]
thanks @adin234, now i'm struggling how can i get the access_token, i already got the code that redirect to me. now i try to send the given code but i didn't receive access_token the the subscriber number to start sms api

**Comment by amsantos** [comment]
hi brian.

the globe labs apis is currently includes messaging, calls, location and
operator billing. gcash api or payments is not included. may we suggest to
go to gcash site: https://www.globe.com.ph/gcash/customer-c and fill ip and
form.

should you have conerns feel free to email api@globelabsbeta.com

regards,

**Comment by adin234** [comment]
@biansor the docs are pretty clear, after getting a code, you have to exchange that for an access token 
```php
    require ('api/PHP/src/GlobeApi.php');
    $globe = new GlobeApi();
    $auth = $globe->auth(
        [KEY],
        [SECRET]
    );
    $token = $auth->getAccessToken([CODE]);
```

**Comment by biansor** [comment]
i am moving now thanks for help, now i want to get text messages and save to my dabatabase, i already get the notify URL and try to insert in database but its inserting empty data  i can't get the text message contain,

**Comment by adin234** [comment]
if you are using php, it is indicated in the docs that you need

```php
 $json = file_get_contents('php://input');
```

to get the message. https://github.com/globelabs/api/blob/master/PHP/docs/sms.md#receiving

**Comment by jopaulam** [comment]
hi, i am new to the sms api, i am still confused of the steps in using it, i want to ask if there are other visual examples of the process

**Comment by adin234** [comment]
@jopaulam  https://github.com/globelabs/api/blob/master/PHP/test/index.php#L3-L23

**Comment by jopaulam** [comment]
Thanks @adin234,but ive encountered another, I realized that my redirect url and notify url is not working, how shud I set these right?

**Comment by jopaulam** [comment]
Another question, can the api send messages to non subscribers?

**Comment by amsantos** [comment]
sadly no.

Subscribers need to opt-in first by sending a "Yes" sms to the access
number.

This restriction is in placed to protect subscribers from getting unwanted
or unsolicited SMSs.

**Comment by jopaulam** [comment]
thanks @amsantos, but i am still confused with the my url's

**Comment by adin234** [comment]
@jopaulam what do you mean it is not working? your notification URL should be something accessible outside. using `http://localhost` as a notification URL obviously wont work since the service obviously can't connect to it. i suggest using ngrok if you dont have a server set up yet. https://github.com/globelabs/api/blob/master/PHP/docs/sms.md#receiving

**Comment by jopaulam** [comment]
Is the code within the url?

**Comment by jopaulam** [comment]
Hello again. I looked at the doumentation but the images from the links are not there, are they gone?

**Comment by amsantos** [comment]
new documentation is found at www.globelabs.com.ph

**Comment by jopaulam** [comment]
Hello again, i want to ask what part of the code that sends messages to many subscribers............i am reiviewing php all over again since i got lost during the development.............thanks in advance

**Comment by jopaulam** [comment]
is this how the group messaging of the api?

**Comment by jopaulam** [comment]
hello po, pa'no gawin yung loop para s ma send sa maraming subscribers.

**Comment by sinnedmi** [comment]
why i'm always redirected to registration screen? how can i send message? maraming salamat po

**Comment by aaez** [comment]
Hi! anyone can help me in receiving messages? i already tried this code:
`$json = file_get_contents('php://input');
    $json = stripslashes($json);
    $values = json_decode($json, true);`
i only get a blank page, when i try to var_dump $json, it says string(0) "".

i can already send messages, my only problem is that i can't get the messages being sent to my app.
hope anyone can help me. thanks in advance.

**Comment by ayophanz** [comment]
Hi, In Receiving SMS (SMS-MO) why my notify url didn't execute?
this is my notify url http://axul.websiteprojectupdates.com/siteToSubscriber/ suppose to be when that url executed my db will update.

as globelab said when subscriber reply or send a message to your shortcode number it will pass data un my notify url

thank you

**Comment by jucevalencia** [comment]
Hi, sorry I am new to this api; is this API for GCash or this is something completely different?

Again sorry I am 100% new on this, I am looking how to integrate with GCash
